title: Siddhant Tewari
logo: /assets/img/sid.jpg
#description: Experienced AI/ML Professional | Two-Time Founder | Ex-McKinsey Management Consultant
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
